---
title: "test"
output: html_document
date: "2024-05-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
library(ggplot2)
library(tidyverse)

options(repos = c(CRAN = "https://cloud.r-project.org"))

data <- read.csv("n_movies.csv")

data2 <- na.omit(data)

genre_frequency <- data2 %>%
  count(genre, sort = TRUE)

chart_3 <- ggplot(data = genre_frequency, aes(x = reorder(genre, n), y = n), fill = x) +
  geom_bar(stat = "identity") +
  labs(title = "Frequency of Different Genres",
       x = "Genre",
       y = "Frequency") +
  theme_minimal()

chart_3
```

```{r}
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)

movies <- read.csv("n_movies.csv")

movies <- movies %>% 
  separate_rows(genre, sep = ",\\s*")

movies$extracted_genre <- word(movies$genre, 1)

genre_count <- movies %>%
  group_by(extracted_genre) %>%
  summarize(frequency = n()) %>%
  arrange(desc(frequency))

# Create the bar graph
ggplot(genre_count, aes(x = reorder(extracted_genre, -frequency), y = frequency)) +
  geom_bar(stat = "identity") +
  labs(title = "Frequency of Movies by Genre",
       x = "Genre",
       y = "Frequency") +
  theme_minimal()


```

